# Driver & Vehicle Service Configuration
spring.application.name=driver-vehicle-service
server.port=${SERVER_PORT:8082}

# MongoDB Database per Service Isolation
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_driver_db}

# JWT Shared Secret
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

# OpenAPI / Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
