# Ride Management Service Configuration
spring.application.name=ride-management-service
server.port=${SERVER_PORT:8083}

# MongoDB Database per Service Isolation
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_ride_db}

# JWT Shared Secret
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

# Downstream Microservices URLs
driver.service.url=${DRIVER_SERVICE_URL:http://localhost:8082}
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8084}

# OpenAPI / Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
